[book]
title = "KRIS Radio"
authors = ["Kris with a K"]
description = "Electromagnetic pollution for a purpose."
multilingual = false
src = "posts"

[build]
build-dir = "docs"
create-missing = false

[preprocess.index]

[preprocess.links]

[output.html]
theme = "posts/theme"
default-theme = "coal"